apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: crossplane-quickstart-vm-with-network
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: quickstart-vm
          base:
            apiVersion: compute.azure.upbound.io/v1beta1
            kind: LinuxVirtualMachine
            spec:
              forProvider:
                adminUsername: adminuser
                adminSshKey:
                  - publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyVbIWIV6yWrWkGJTcQ8p9k8QLdS3OFMzjrNxgEgolZl3jqhPACZXPbJrgnVcLxZits2kWAXQFhNXTkYFcuaLwLSaqJbffgQDwaTufG5DxcNWlpWrTGcR1etpCwzOV2nwYx8KPSH/yXudtcFQcuaApCZ8H8se4ywLu8sUykUfvU1PAVi3QrEvaELZebawCrFqNMKzd60aMfzsW45ateTHJjjn/ZthRD89H0X0niK/s30L++t9gxLv/Ec2bCFcLC8IaU6RNYEbKMzgPdQYyxizkn3Ojly1TP+nWhRV1sVxp42cSaoGKg5CSRFIr2d6HbcvTC80mYapJr6jmJ1jREFAvZqGc/1SUcmzTcp59MwAIiQO9Zo6MvsFzvHc/sZ/LvFt3Efcz9+0xeTla9Fwb+augzAe8su+eYyg7zgnejL7knJnq1HchLXdqN0KB0Aj7X5I4nO6O0IRI7sUJ7athoVW6N4rr0NJfEP4PL01Ml0on8K1P01dVdPcHevddhEZgIxlTV0YZDKIk9FL+Qam/B8wxRYRo2GErjgAT2oUCP+xG7RBe/hMiPuGt07gtRWlnRgV/FcdgnWEKZsjYlwBhU6l+QLkvTEsn5pjaS3M0rFV9cglic9NRNVLF38cjJGk9HEGMlbp/Mn8dF2mGBHWepBHOh4+jvsI1HX6Sa1zh/Any6w== clusterapi@k3s.com
                    username: adminuser
                location: "West US"
                osDisk:
                  - caching: ReadWrite
                    storageAccountType: Standard_LRS
                resourceGroupNameSelector:
                  matchControllerRef: true
                size: Standard_B2ms
                sourceImageReference:
                  - offer: debian-11
                    publisher: Debian
                    sku: 11-backports-gen2
                    version: latest
                networkInterfaceIdsSelector:
                  matchControllerRef: true
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    EU: "Sweden Central"
                    US: "West US"
        - name: quickstart-nic
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: NetworkInterface
            spec:
              forProvider:
                ipConfiguration:
                  - name: crossplane-quickstart-configuration
                    privateIpAddressAllocation: Dynamic
                    subnetIdSelector:
                      matchControllerRef: true
                location: "West US"
                resourceGroupNameSelector:
                  matchControllerRef: true
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    EU: "Sweden Central"
                    US: "West US"
        - name: quickstart-subnet
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: Subnet
            spec:
              forProvider:
                addressPrefixes:
                  - 10.0.1.0/24
                virtualNetworkNameSelector:
                  matchControllerRef: true
                resourceGroupNameSelector:
                  matchControllerRef: true
        - name: quickstart-network
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: VirtualNetwork
            spec:
              forProvider:
                addressSpace:
                  - 10.0.0.0/16
                location: "West US"
                resourceGroupNameSelector:
                  matchControllerRef: true
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    EU: "Sweden Central"
                    US: "West US"
        - name: crossplane-resourcegroup
          base:
            apiVersion: azure.upbound.io/v1beta1
            kind: ResourceGroup
            spec:
              forProvider:
                location: West US
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    EU: "Sweden Central"
                    US: "West US"
  compositeTypeRef:
    apiVersion: compute.example.com/v1alpha1
    kind: VirtualMachine
